import React from "react";
import { Layout } from "antd";

const { Sider: AntdSider } = Layout;

export default function Sider() {
  return (
    <AntdSider style={{ backgroundColor: "white" }}>
      SIDER SIDERSIDERSIDER SIDER SIDER SIDER SIDER SIDER SIDERSIDERSIDER SIDER
      SIDER SIDERSIDERSIDER SIDER SIDER SIDER SIDER SIDER SIDERSIDERSIDER SIDER
      SIDER SIDERSIDERSIDER SIDER SIDER SIDER SIDER SIDER SIDER SIDER SIDER
      SIDER SIDERSIDERSIDER SIDER SIDER SIDER SIDER SIDER SIDERSIDERSIDER SIDER
      SIDER SIDERSIDERSIDER SIDER SIDER SIDER SIDER SIDER SIDER SIDER SIDER
      SIDER
    </AntdSider>
  );
}
